spring.application.name=technical

# Logging
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/indomarco
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# SQL Initialization
spring.sql.init.mode=always

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

# JWT
jwt.secret=abcdefghijklmnopqrstuvxyzabcdefghijklmnopqrstuvxyz
jwt.expiration=3600000
